server:
  port: 8300

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/json-poc
    username: postgres
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generateDdl: true
    showSql: true
    hibernate:
      ddl-auto: update

